rssm_config = {
    'rssm_info': {'rssm_type':'discrete', 'num_ensemble':7, 'hidden_size':512, 'deter_size':512, 'stoch_size':30, 'category_size':32, 'class_size':32, 'min_std':0.1, 'activation':'elu'},
    'obs_embedding_size': 1024,
    'obs_encoder': {'activation':'elu', 'kernels':[4, 4, 4, 4], 'depth':48},
    'obs_decoder': {'activation':'elu', 'kernels':[5, 5, 6, 6], 'depth':48},
    'reward_model': {'layers':4, 'node_size':1024, 'dist':'normal', 'activation':'elu', 'dropout': 0.2},
    'discount_model': {'layers':4, 'node_size':1024, 'dist':'binary', 'activation':'elu', 'dropout': 0.2},
    'action_model': {'layers':4, 'node_size':1024, 'activation':'elu', 'dropout': 0.2},
    'kl_info': {'use_kl_balance': True, 'kl_balance_scale': 0.8, 'use_free_nats': True, 'free_nats': 1.0},
    'loss_scale': {'kl':0.5, 'reward':0, 'discount':0, 'action': 1.0},
    'seq_len': 20,
    'grad_clip_norm': 100,
    'model_lr': 1e-4,
    'model_batch_size': 64,
    'model_train_steps': 300000,
}